apiVersion: skaffold/v1
kind: Config
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: yoyota/<CHARTNAME>
          sync:
            manual:
              - src: "src/**/*.js"
                dest: .
          docker:
            target: install
    deploy:
      helm:
        releases:
          - name: <CHARTNAME>
            chartPath: helm
            setValueTemplates:
              develop.enabled: true
              develop.repository: "{{.IMAGE_NAME}}"
              develop.tag: "{{.DIGEST_HEX}}"
  - name: run
    activation:
      - command: run
    build:
      artifacts:
        - image: yoyota/<CHARTNAME>
    deploy:
      helm:
        releases:
          - name: <CHARTNAME>
            chartPath: helm
            setValueTemplates:
              image.repository: "{{.IMAGE_NAME}}"
              image.tag: "{{.DIGEST_HEX}}"